const constants = {
	HYDRATE: 'MAIN_HYDRATE',
	LOGOUT: 'MAIN_LOGOUT',
	ADD_SUBDOMAIN: 'MAIN_ADD_SUBDOMAIN',
	UPDATE_ADD_SUBDOMAIN: 'MAIN_UPDATE_ADD_SUBDOMAIN',
	UPDATE_SUBDOMAINS: 'MAIN_UPDATE_SUBDOMAINS',
	REMOVE_SUBDOMAIN: 'MAIN_REMOVE_SUBDOMAIN',
	UPDATE_SUBDOMAIN_TOKEN: 'MAIN_UPDATE_SUBDOMAIN_TOKEN'
};

export default constants;
